### ISSUE TITLE
Feature Request: Dynamic Table of Contents showing Headings of a Node's document

### ISSUE THREAD

**Issue by erros84** [bryanph/GeistMap#111]
Since there is so much empty space to the left and right of a Node's document, it would be nice to use some of that space for a floating table of contents showing the headings. Maybe it could be updated with each save.

Starting with H1 (https://github.com/bryanph/Geist/issues/110) would also make it easier to manage this TOC.

**Comment by bryanph** [comment]
Thanks for the suggestion, I have moved it to #57 and will close this issue

You are right that on bigger screens more can be done with the available space.

**Comment by bryanph** [comment]
@erros84 The outline view kind of serves this purpose now, do you agree?

**Comment by bryanph** [comment]
See https://trello.com/c/lz6UvLoo/4-smart-headers-in-the-content
