### ISSUE TITLE
Login button covered by project drawer [BUG]

### ISSUE THREAD

**Issue by Ri73** [bryanph/GeistMap#178]
It would be better for it to show up on top of the button. I observed this behavior in Firefox Quantum.
![screenshot from 2018-02-23 14-36-53](https://user-images.githubusercontent.com/12220708/36608381-6dcd5d76-18a8-11e8-9360-6baf4c88cc3f.png)

**Comment by bryanph** [comment]
Fixed in c3dd1141c1948796c954206006fd795c3fcc56eb
