### ISSUE TITLE
Ovelapping text [BUG]

### ISSUE THREAD

**Issue by Ri73** [bryanph/GeistMap#179]
The nodes' titles tend to overlap. That's a problem specially while in hierarchical view because it diminishes readability and hinders your ability to click on obscured nodes.
![Overlapping while in link view](https://screenshotscdn.firefoxusercontent.com/images/9a377843-2319-494c-a5b1-adbb234b2fa6.png)
![Overlapping while in hierarchical view](https://screenshotscdn.firefoxusercontent.com/images/9fdcb67e-08fc-412c-8d3f-a13ee69c61dc.png)

# Proposed Solutions

* Auto-wrap text
* Automatic spacing to avoid overlap

**Comment by bryanph** [comment]
A first attempt at a solution is done in 0b49a190a02760ab44a0e143e129429d5a628ce3
The text now wraps and also changes its font size when the title gets longer
