### ISSUE TITLE
Easier navigation for links between collections

### ISSUE THREAD

**Issue by bryanph** [bryanph/GeistMap#5]
Right now because you are mostly working inside a collection detail view and the detail view right now only shows exactly the nodes that are in that collection, it is difficult to see to which other nodes outside the collection the nodes connect.

A few options for this:

- [ ] By default fetch the nodes in the collection AND fetch nodes with a distance 1 from the collection
- [ ] Have a toggle for the option above which is disabled by default (or enabled?)
- [ ] Don't show the nodes that are linked to but rather the collections that the nodes link to on the outside of the graph
- [ ] Change design of the graph to include an ability to pull in neighboring nodes for any nodes (#29)

**Comment by bryanph** [comment]
In Collection.get:
* fetch all nodes with _all_ edges by default, provide a toggle for also fething the neighbouring edges (or we can just always fetch neighbours as well)
* in the front-end filter nodes and edges that are in fact exactly _IN_ the collection (have the result stored in the reducer, so including the neighbouring edges) => maybe on getting the data result, mark nodes that are not actually IN the collection with an isInCollection flag or something, same for edges
*

**Comment by erros84** [comment]
Would it be possible to show those 1-step links to units outside the collection as dotted lines?

**Comment by bryanph** [comment]
This is implemented now with the new hierarchical graph
