### ISSUE TITLE
New project name

### ISSUE THREAD

**Issue by bryanph** [bryanph/GeistMap#95]
Something that has an available .com or .io domain.

**Comment by vkeusebio** [comment]
**Mendim** [Albanian] (*.io available*): opinion, thought, thinking, mind, sentiment, idea
**Gedanke** [German] (*.io available*): thought, idea, concept, reflection, sentiment, reflexion

**Comment by bryanph** [comment]
I'm fine with Geistmap honestly and I don't think it will really matter in the end
